### ISSUE TITLE
Extra Resources not found

### ISSUE THREAD

**Issue by b509** [crossplane-contrib/function-extra-resources#25]
### What happened?
Configured Extra-Resources as part of a composition but only one of my two custom resources is found. This used to work, so this ticket is more about options to troubleshoot (e.g. increasing the log level in extra-resource function, which resources to look at to get more details, turning off TLS in grpc so I can use wireshark to troubleshoot the grpc traffic using ksniff, ... any other pointers what I can do to find this issue)

### How can we reproduce it?
Composition
 ```yaml
pipeline:
  - step: pull-provider-configs
    functionRef:
      name: function-extra-resources
    input:
      apiVersion: extra-resources.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        extraResources:
          - kind: Secret
            into: secrets
            apiVersion: v1
            type: Selector 
            selector:
              minMatch: 1
              maxMatch: 100
              matchLabels:
                - key: type
                  type: Value
                  value: provider-credentials
          - kind: Role
            into: roles
            apiVersion: role.keycloak.crossplane.io/v1alpha1
            type: Selector
            selector:
              minMatch: 1
              maxMatch: 20
              matchLabels:
                - key: type
                  type: Value
                  value: modifiedrole
... more steps
```
1 secret with sought annotation
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials-one
  namespace: crossplane-system
  labels:
    type: provider-credentials
type: Opaque
stringData:
  credentials: |
    {
      "client_id": "admin-cli",
      "url": "http://keycloak-keycloakx-http.default.svc.cluster.local",
      "base_path": "/",
      "realm": "master",
      "username": "admin",
      "password": "admin"
    }
```
1 Keycloak role with sought annotation
```yaml
apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  name: my-modified-role
  namespace: crossplane-system
  labels:
    type: modifiedrole
spec:
  forProvider:
    name: default-roles-master-1
    realmId: master
    compositeRoles: []
  deletionPolicy: Orphan
  providerConfigRef:
    name: keycloak-provider-config
```
For me the secret is found, but the role not, even though I can find it in K8s just fine using ``k get roles.role.keycloak.crossplane.io -l 'type in (modifiedrole)'``

### What environment did it happen in?
Function version: `xpkg.upbound.io/crossplane-contrib/function-extra-resources:v0.0.3`
Crossplane image:  `xpkg.upbound.io/crossplane/crossplane:v1.16.0`
Kubernetes version: 
```
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.8+k3s1
```
Kubernetes Distribution: `k3d`
