### ISSUE TITLE
type: Reference complains about empty namespace

### ISSUE THREAD

**Issue by JohanSandblom3** [crossplane-contrib/function-extra-resources#27]
### What happened?
When trying to get extra resource using `Reference` a ReconcileError happens.

### How can we reproduce it?
composition step:
```yaml
  - step: run-function-extra-resources
    functionRef:
      name: function-extra-resources
    input:
      apiVersion: extra-resources.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        extraResources:
        - apiVersion: v1
          into: my-secret-into
          kind: Secret
          ref:
            name: my-secret
          type: Reference
```

Status of XR:
```yaml
status:
  conditions:
  - lastTransitionTime: "2024-08-30T12:05:20Z"
    message: 'cannot compose resources: fetching resources for my-secret-into: cannot
      get extra resource by name: an empty namespace may not be set when a resource
      name is provided'
    reason: ReconcileError
    status: "False"
    type: Synced
```

The very secret secret
```sh
kubectl create secret generic my-secret --from-literal=secret=value
```

### What environment did it happen in?
Function version: v0.0.3
Crossplane version: 1.16.0-up.1

All running locally in a kind cluster.

* Cloud provider or hardware configuration
* Kubernetes version v1.25.3
* Kubernetes distribution kind
* OS Ubuntu 22.04.3 LTS on WSL2
* Kernel Linux CND1323TQQ 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
