### ISSUE TITLE
Extra resources fails when using selector on field generated by previous step

### ISSUE THREAD

**Issue by JakobGSvendsen** [crossplane-contrib/function-extra-resources#31]
## What happened?
I am trying to use a value from a extra resource to find another extra resource.
Since I couldnt find a way to map it inside one instance of the function in a pipeline, I decided to make a "predeploy" template step that simply reads the value and outputs to "status".

Then after that step I want to run a second extra resroucce step that uses the status value to get the additional extra resource, but it fails.

I thought it worked, but it turned out it only worked cause I updated it on already existing resources that did already have the status set.

For new resource I get:

message: 'cannot compose resources: pipeline step "pull-extra-resources-identity" returned a fatal result: could not build extra resource requirements: cannot get value from field path "status.iitech.shortName": status.iitech: no such field'

Is it not possible to make it like this? I thought it would be as it is a "pipeline". 
if not, is there any other way that I can use a value from my "blueprint" extra resource to find my "userassignedIdentity" resource?

### How can we reproduce it?
This is my composition, the field I am setting is defined in the compositeresourcedefintion:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: iitech-mongodb
spec:
  compositeTypeRef:
    apiVersion: iitech.dk/v1
    kind: xMongoDB
  mode: Pipeline
  pipeline:
  - step: pull-extra-resources
    functionRef:
      name: function-extra-resources
    input:
      apiVersion: extra-resources.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        extraResources:
          - kind: Blueprint
            into: blueprint
            apiVersion: iitech.dk/v1alpha1
            type: Selector
            selector:
              maxMatch: 1
              minMatch: 1
              matchLabels:
                - key: "iitech.dk/backstage-catalog-entity"
                  type: FromCompositeFieldPath
                  valueFromFieldPath: spec.snowId
          - kind: ConfigMap
            into: env
            apiVersion: v1
            type: Selector
            selector:
              maxMatch: 1
              minMatch: 1
              matchLabels:
                - key: name
                  type: Value
                  value: env
  - step: go-templates-predeploy
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: FileSystem
      fileSystem:
        dirPath: /templates/predeploy.tpl
  - step: pull-extra-resources-identity
    functionRef:
      name: function-extra-resources
    input:
      apiVersion: extra-resources.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        extraResources:
          - kind: Blueprint
            into: blueprint
            apiVersion: iitech.dk/v1alpha1
            type: Selector
            selector:
              maxMatch: 1
              minMatch: 1
              matchLabels:
                - key: "iitech.dk/backstage-catalog-entity"
                  type: FromCompositeFieldPath
                  valueFromFieldPath: spec.snowId
          - kind: ConfigMap
            into: env
            apiVersion: v1
            type: Selector
            selector:
              maxMatch: 1
              minMatch: 1
              matchLabels:
                - key: name
                  type: Value
                  value: env
          - kind: UserAssignedIdentity
            into: identity
            apiVersion: managedidentity.azure.upbound.io/v1beta1
            type: Selector
            selector:
              maxMatch: 1
              minMatch: 1
              matchLabels:
                - key: "iitech.dk/shortName"
                  type: FromCompositeFieldPath
                  valueFromFieldPath: status.iitech.shortName
  - step: go-templates-deploy-rg
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: FileSystem
      fileSystem:
        dirPath: /templates/resourcegroup.tpl
  - step: go-templates-deploy-account
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: FileSystem
      fileSystem:
        dirPath: /templates/cosmosdb.tpl
  - step: go-templates-deploy-rbac
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: FileSystem
      fileSystem:
        dirPath: /templates/cosmosdb-roleassignment.tpl
  - step: automatically-detect-ready-composed-resources
    functionRef:
      name: function-auto-ready
```

my predeploy template looks like this:
```go
{{/* Extra resources */}}
{{- $blueprint := index (index .context "apiextensions.crossplane.io/extra-resources") "blueprint" 0}}
---
apiVersion: iitech.dk/v1
kind: xMongoDB
metadata:
  annotations:
    gotemplating.fn.crossplane.io/composition-resource-name: status-shortname
status:
  iitech:
    shortName: {{ $blueprint.spec.shortName }} 
```

### What environment did it happen in?
Function version: v0.0.3

**Comment by phisco** [comment]
`function-extra-resources` reads from the `observed` Composite resource, which is the one actually existing in the cluster, not the `desired` one, which would be the one you just set `status.iitech.shortName` to and is passed down the pipeline.

We should probably add a `FromContext` source, so that you could use the Context to pass the value instead of going through the XR's status.

However, I'd suggest you to have a look at the support for Context and Extra resources in `function-go-templating`, see [here](https://docs.crossplane.io/latest/concepts/compositions/#how-composition-functions-work), functions can iteratively request for extra resources, as long as they get stable in the max amount of iterations allowed, so with some `IF`s, you should be able to do what you are asking for.

**Comment by JakobGSvendsen** [comment]
Hello again!

I upgraded the go-templating and use this as the predeploy.tpl
`
{{/* Extra resources */}}
{{- $blueprint := index (index .context "apiextensions.crossplane.io/extra-resources") "blueprint" 0}}
---
apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
kind: Context
data:
    shortName: {{ $blueprint.spec.shortName }} 
`

but I get
 Warning  ComposeResources   4m19s (x13 over 14m)   defined/compositeresourcedefinition.apiextensions.crossplane.io  cannot compose resources: pipeline step "pull-extra-resources-identity" returned a fatal result: verifying and sorting extra resources: cannot find expected extra resource "identity"      
 
 
 This is my code for extra resources with "FromContext":
 
`
 - step: pull-extra-resources-identity
    functionRef:
      name: function-extra-resources
    input:
      apiVersion: extra-resources.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        extraResources:
          - kind: Blueprint
            into: blueprint
            apiVersion: iitech.dk/v1alpha1
            type: Selector
            selector:
              maxMatch: 1
              minMatch: 1
              matchLabels:
                - key: "iitech.dk/backstage-catalog-entity"
                  type: FromCompositeFieldPath
                  valueFromFieldPath: spec.snowId
          - kind: ConfigMap
            into: env
            apiVersion: v1
            type: Selector
            selector:
              maxMatch: 1
              minMatch: 1
              matchLabels:
                - key: name
                  type: Value
                  value: env
          - kind: UserAssignedIdentity
            into: identity
            apiVersion: managedidentity.azure.upbound.io/v1beta1
            type: Selector
            selector:
              maxMatch: 1
              minMatch: 1
              matchLabels:
                - key: "iitech.dk/shortName"
                  type: FromContext
                  valueFromFieldPath: shortName
`
 
I also tried "data.shortName"

Do you know what I am doing wrong?

(please let me know if you want me to post all the templates in this pipeline).

P.s. I am trying to get crossplane CLI into our environment but waiting for approval to have it available in our repository. Maybe I can see more if I try the cli to test the composition?

**Comment by JakobGSvendsen** [comment]
So I looked at it and now I got a the issue that I cannot find the 

Warning  ComposeResources   19s (x6 over 44s)  defined/compositeresourcedefinition.apiextensions.crossplane.io  cannot compose resources: pipeline step "pull-extra-resources-identity" returned a fatal result: verifying and sorting extra resources: cannot find expected extra resource "identity"        

I used this in the predeploy.tpl in gotemplating

```
{{/* Extra resources */}}
{{- $blueprint := index (index .context "apiextensions.crossplane.io/extra-resources") "blueprint" 0}}
---
apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
kind: Context
data:
    shortName: {{ $blueprint.spec.shortName }} 
```


and here is the new composition pipeline extra resources step :

```
  - step: pull-extra-resources-identity
    functionRef:
      name: function-extra-resources
    input:
      apiVersion: extra-resources.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        extraResources:
          - kind: Blueprint
            into: blueprint
            apiVersion: iitech.dk/v1alpha1
            type: Selector
            selector:
              maxMatch: 1
              minMatch: 1
              matchLabels:
                - key: "iitech.dk/backstage-catalog-entity"
                  type: FromCompositeFieldPath
                  valueFromFieldPath: spec.snowId
          - kind: ConfigMap
            into: env
            apiVersion: v1
            type: Selector
            selector:
              maxMatch: 1
              minMatch: 1
              matchLabels:
                - key: name
                  type: Value
                  value: env
          - kind: UserAssignedIdentity
            into: identity
            apiVersion: managedidentity.azure.upbound.io/v1beta1
            type: Selector
            selector:
              maxMatch: 1
              minMatch: 1
              matchLabels:
                - key: "iitech.dk/shortName"
                  type: FromContext
                  valueFromFieldPath: shortName
```

I also tried data.shortName.

what is the correct syntax?
