### ISSUE TITLE
Is it correct approach to tie together 2 claims?

### ISSUE THREAD

**Issue by artisticcheese** [crossplane-contrib/function-extra-resources#39]
Hello,

I was forwarded here telling me that this function shall solve my issue which is::
I have 2 different composite resources and 2 claims in names space. One is parent resources and another one is child resource which depends and need to read some data from parent resource on that one is created.
I have been told that this function shall help in such cases but I'm having hard time understanding how this would work for me situation.
I have claim in namespace `crossplane-demo`
```
PS C:\Users\gregory> k get demoapiclaim.apim.company.com/my-demo-api-claim -n crossplane-demo -o yaml
status:
  apiManagementName: apim-service-reference
  apiName: my-demo-api-claim-svlcb-kxwqq
  resourceGroupName: apim-rg-reference
```
Which creates bunch of resources in cluster scope like below
```
PS C:\Users\gregory> k get api.apimanagement.azure.upbound.io/my-demo-api-claim-svlcb-kxwqq -o yaml
apiVersion: apimanagement.azure.upbound.io/v1beta2
kind: API
metadata:
  annotations:
    crossplane.io/composition-resource-name: api
    crossplane.io/external-create-pending: "2025-05-16T20:48:33Z"
    crossplane.io/external-create-succeeded: "2025-05-16T20:48:33Z"
    crossplane.io/external-name: my-demo-api-claim-svlcb-kxwqq
  generateName: my-demo-api-claim-svlcb-
  generation: 3
  labels:
    crossplane.io/claim-name: my-demo-api-claim
    crossplane.io/claim-namespace: crossplane-demo
    crossplane.io/composite: my-demo-api-claim-svlcb
  name: my-demo-api-claim-svlcb-kxwqq
```
I need to create another claim for different resource type in the same namespace and read status field of parent resource `my-demo-api-claim` (for example `apiName`), Can this function help?
