### ISSUE TITLE
Add logging to PODs

### ISSUE THREAD

**Issue by artisticcheese** [crossplane-contrib/function-extra-resources#40]
There is no logs generated by function-extra-resource pods

```
PS C:\Users\gregory> k logs -n crossplane function-extra-resources-fa66e8ab9f79-6bc474c7f6-rbx46
PS C:\Users\gregory>
```

**Comment by bobh66** [comment]
The function takes a `--debug` option that should enable debug logging.

**Comment by artisticcheese** [comment]
How do I add this? Example below did not seem to work

```
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-extra-resources
spec:
  package: xpkg.crossplane.io/crossplane-contrib/function-extra-resources:v0.0.3
  config:
    args: ["--debug"]
```

**Comment by bobh66** [comment]
Use a `DeploymentRuntimeConfig` to set the debug arg as discussed here:  https://docs.crossplane.io/latest/concepts/providers/#runtime-configuration

**Comment by artisticcheese** [comment]
Modified as follows
```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: debug-config
spec:
  args:
    - --debug
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-extra-resources
spec:
  package: xpkg.crossplane.io/crossplane-contrib/function-extra-resources:v0.0.3
  controllerConfigRef:
    name: debug-config
```

Seeing following logs, does not seem to be outputing debug level logs. Is it expected?

```
{"level":"info","ts":1747671323.8185213,"caller":"fn/fn.go:38","msg":"Running function","tag":""}
{"level":"info","ts":1747671353.851392,"caller":"fn/fn.go:38","msg":"Running function","tag":""}
{"level":"info","ts":1747671383.8683193,"caller":"fn/fn.go:38","msg":"Running function","tag":""}
{"level":"info","ts":1747671413.8909385,"caller":"fn/fn.go:38","msg":"Running function","tag":""}
{"level":"info","ts":1747671443.918391,"caller":"fn/fn.go:38","msg":"Running function","tag":""}
{"level":"info","ts":1747671473.939417,"caller":"fn/fn.go:38","msg":"Running function","tag":""}
```
