### ISSUE TITLE
Can not pull external-resource

### ISSUE THREAD

**Issue by artisticcheese** [crossplane-contrib/function-extra-resources#41]
### What happened?
Trying to get external resource but it's failing for whatever reason

### How can we reproduce it?
```
    - step: pull-extra-resources
      functionRef:
        name: function-extra-resources
      input:
        apiVersion: extra-resources.fn.crossplane.io/v1beta1
        kind: Input
        spec:
          extraResources:
            - kind: API
              into: demoapi-reference
              apiVersion: apimanagement.azure.upbound.io/v1beta2
              type: Selector
              selector:
                maxMatch: 2
                minMatch: 1
                matchLabels:
                  - key: crossplane.io/claim-namespace
                    type: Value
                    value: crossplane-demo
```

Log from function
```
2025-05-20T20:56:40.814Z	DEBUG	fn/fn.go:72	No extra resources present, exiting	{"requirements": "extra_resources:{key:\"demoapi-reference\"  value:{api_version:\"apimanagement.azure.upbound.io/v1beta2\"  kind:\"API\"  match_labels:{labels:{key:\"crossplane.io/claim-namespace\"  value:\"crossplane-demo\"}}}}"}
```

This resource exists and pulls up properly 

```
PS C:\Users\gregory> kubectl get API --selector=crossplane.io/claim-namespace=crossplane-demo
NAME                            SYNCED   READY   EXTERNAL-NAME                   AGE
my-demo-api-claim-h8dqr-4fc25   True     True    my-demo-api-claim-h8dqr-4fc25   25h
```
### What environment did it happen in?
Function version: 0.0.3
